version: '3'

volumes:
  weather_data:
      driver: local

services:
  fastapi_weather:
    container_name: fastapi_weather
    build:
      context: ./
      # args: 
      #   TEST: Test
    image: python
    ports:
      - 8081:8080
    networks:
      - weather_dev
  elastic_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic_container
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - weather_data:/usr/share/elasticsearch/elastic_data
    networks:
      - weather_dev
    ports:
      - 9200:9200
networks:
  weather_dev:
    external:
      name: weather_dev